name: "ci"
on:
  workflow_dispatch:
  push:
      branches-ignore:
          - "release-please-**"
          - "main"

permissions:
  contents: read # for checkout
  pull-requests: read  # for comments

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
            
      - name: Commit Linter
        uses: wagoid/commitlint-github-action@v5.4.1    

      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: bootstrap
        run: npm run bootstrap

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build

      - name: test
        run: npm run test
