name: publish
on:
  workflow_dispatch:
    inputs:
      force:
        description: Used to force a publish
        required: true
        type: boolean
        default: false
  push:
      branches:
          - main
    

permissions:
  contents: write # for checkout and tag
  actions: write # updating envs
  pull-requests: write # for comments
  packages: write # for publish
  id-token: write

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"      

      - name: Commit Linter
        uses: wagoid/commitlint-github-action@v5.4.1

      - uses: google-github-actions/release-please-action@v3
        name: release-please
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: "@swimlane/docker-reference"
      
      - name: bootstrap
        run: npm run bootstrap

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: publish
        if: ${{ steps.release.outputs.release_created || inputs.force }}
        run: |
          npm publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUSH_TOKEN }}

